server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: 'Decision Engine'
  profiles:
    active: test
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Tallinn
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${APP_DB_HOST:decisionengine-db}:${APP_DB_PORT:5432}/${APP_DB:decisionengine}
    username: ${APP_DB_USER:root}
    password: ${APP_DB_PASSWORD:root}

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /decision-engine-swagger-ui.html
